import { flags, SfdxCommand } from '@salesforce/command';
import { Messages, SfdxError } from '@salesforce/core';
import { AnyJson } from '@salesforce/ts-types';
import { exec } from 'child_process';
const fs = require('fs-extra');

export default class listObjects extends SfdxCommand {

  public static description = 'Lists the objects in the org as per specified de-limiter';

  protected static flagsConfig = {
	delimiter: flags.string({ char: 'd', description: 'Delimiter', required: false, default: ',' }),
	sobjecttypecategory: flags.string({ char: 'c', description: 'The type of objects to list: all, custom, or standard.', required: false, default:'custom'}),
	customadditions: flags.string({ char: 'a', description: 'Additions apart from the ones generated by utility(Comma seperated)', required: false, default: '' }),
	path: flags.string({char: 'p', description: 'path to the result file',required:false,default:'inputs.txt'}),
	startswithfilter: flags.string({char: 's', description: 'Includes objects that starts with specific keywords(Comma seperated)',required:false,default:''}),
	endswithfilter: flags.string({char: 'e', description: 'Includes objects that ends with specific keywords(Comma seperated)',required:false,default:''})
  };

  // Comment this out if your command does not require an org username
  protected static requiresUsername = true;
 
  // Comment this out if your command does not support a hub org username
  protected static supportsDevhubUsername = false;

  // Set this to true if your command requires a project workspace; 'requiresProject' is false by default
  protected static requiresProject = false;

	public async run(): Promise < AnyJson > {

		console.log('Process initiated.This may take a while...');

		exec('sfdx force:schema:sobject:list --json -c ' + this.flags.sobjecttypecategory + ' -u ' + this.org.getUsername(), (error, stdout, stderr) => {
			
			if (error) {
				console.error(`exec error: ${error}`);
				return;
			}
			var response = JSON.parse(stdout);
			var results = response.result;
			
			if(this.flags.startswithfilter){
				
				var startswithfilter = this.flags.startswithfilter.split(',');
				results = results.filter(function(result) {
					for (var i = 0; i < startswithfilter.length; i++) {
						if(result.startsWith(startswithfilter)){
							return true;
						}
					}
					return false;
				});
			}
			
			if(this.flags.endswithfilter){
				var endswithfilter = this.flags.endswithfilter.split(',');
				results = results.filter(function(result) {
					for (var i = 0; i < endswithfilter.length; i++) {
						if(result.endsWith(endswithfilter)){
							return true;
						}
					}
					return false;
				});
			}
			
			if (this.flags.customadditions){
				results = Array.from(new Set(results.concat(this.flags.customadditions.split(','))));
			}
			
			var contents = results.join(this.flags.delimiter);
			fs.outputFileSync(this.flags.path, contents);
			console.log('Success! Path: '+this.flags.path);

		});
	}
}
